### PR TITLE
Fix issue #23

### PR DESCRIPTION
**Pull request by MaxtorCoder**
Added `archives-index-size` to fix the CDNConfig error popping up when launching WoW.

### CODE REVIEW

**Comment by okwinza** [comment]
@MaxtorCoder Not sure why but i keep getting this every time i'm trying to rebuild the index after building your fork.
```
Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at CASCEdit.Handlers.RootHandler..ctor(Stream data, LocaleFlags locale, UInt32 minimumid) in E:\okwinza\coding-other\CASCEdit\Handlers\RootHandler.cs:line 57
   at CASCEdit.CASContainer.OpenRoot(LocaleFlags locale, UInt32 minimumid) in E:\okwinza\coding-other\CASCEdit\CASContainer.cs:line 226
   at CASCHost.DataWatcher.UpdateCASCDirectory(Object obj) in E:\okwinza\coding-other\CASCHost\DataWatcher.cs:line 148
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
```

AppSettings.json
```
{
  "AppSettings": {
    "MinimumFileDataId": 2500000,
    "BNetAppSupport": false,
    "StaticMode": false,
    "RebuildPassword": "",
    "HostDomain": "localhost:5100",
    "CDNs": [],
    "SqlConnection": "server=127.0.0.1;uid=root;pwd=root;database=caschost",
    "PatchUrl": "http://us.patch.battle.net:1119/wow",
    "Locale": "engb",
    "DirectoryHash": [
      "0aa8acdad03fa93a760d6a5824e1f0a3",
      "89a7085aa643b8a200eef77c25d20439"
    ]
  }
}
```

**Comment by MaxtorCoder** [comment]
Are you using 8.0.1?

**Comment by okwinza** [comment]
i'm using current retail version `8.2.0:30993`.
Though it does look like the current caschost version does not support the lastest casc changes.

**Comment by MaxtorCoder** [comment]
Yeah well that does not work. Nor gonna update it to 8.2.
There are CASC changes in 8.2 which stop you from using CASCHost now until someone updates it.

**Comment by okwinza** [comment]
@MaxtorCoder i suppose wowdev.wiki doesn't reflect those changes yet, does it?

**Comment by MaxtorCoder** [comment]
They do.
That is like the first place where changes go 😂

**Comment by okwinza** [comment]
Just noticed that this fix does not cover force rebuild command (/rebuild).
It still leads to the same issue upon client startup.

**Pull request closed without merging**
